
***
*Solution*: 

```{r sim-mix-a, cache=TRUE, echo=TRUE, eval=TRUE}
  
  # (a)

  sim_poisson_mix_2 <- function(lambda_1, lambda_2, p){
    
    x_bernoulli <- rbinom(n = 1, size = 1, prob = p)
    
    if(x_bernoulli == 1L){
      
      z_pois <- rpois(n = 1, lambda = lambda_1)
    
    } else {
      
      z_pois <- rpois(n = 1, lambda = lambda_2)
      
    }
    
    return(z_pois)
    
    # there are more efficient ways to code this...
    # this code emphasises the construction of the
    # random variable, but is not vectorised.
    
  }

  lambda_1 <- 4
  lambda_2 <- 10
  p <- 0.4

  pmix_samples <- replicate(n = 1000, 
     sim_poisson_mix_2(lambda_1 = lambda_1, 
                       lambda_2 = lambda_2, 
                       p = p)
     )


  # theoretical mean and variance
  mean_poisson_mix_2 <- function(lambda_1, lambda_2, p){
    
    p * lambda_1 + (1 - p) * lambda_2
    
  }
  
  var_poisson_mix_2 <- function(lambda_1, lambda_2, p){
    
    p * lambda_1 + (1 - p) * lambda_2 +  
    p * (1 - p) * (lambda_1 - lambda_2)^2
    
  }
  
  mean_poisson_mix_2(lambda_1 = lambda_1, 
                     lambda_2 = lambda_2, 
                     p = p)
  
  var_poisson_mix_2(lambda_1 = lambda_1, 
                    lambda_2 = lambda_2, 
                    p = p)

  
  # mean and variance by simulation:
  mean(pmix_samples)
  var(pmix_samples)

```

```{r sim-mix-,  fig.margin=TRUE, fig.width=4, fig.height=4, cache=TRUE, eval = TRUE, echo=TRUE, fig.cap= "Histogram of Poisson mixture distribution with two components and density overlayed."}
  
  # (b)

  pmf_poisson_mix_2 <- function(z, lambda_1, lambda_2, p){
    
    p * dpois(x = z, lambda = lambda_1) + 
      (1 - p) * dpois(x = z, lambda = lambda_2)
    
  }

  ggplot() + 
    
    geom_histogram(aes(x = pmix_samples, y = ..density..), 
                   binwidth = 1, colour = "white", 
                   data = pmix_samples_df) +
    
    stat_function(aes(x = 0:21), n = 22, geom = "point",
                  fun = pmf_poisson_mix_2, 
                  args = list(lambda_1 = lambda_1, 
                              lambda_2 = lambda_2, 
                              p = p)
                  )
    

```

```{r sim-mix-c, fig.margin=TRUE, fig.width=4, fig.height=4, cache=TRUE, eval = TRUE, echo=TRUE, fig.cap= "Histogram of Poisson mixture distribution with four components"}
  
  # (c)

  sim_poisson_mix <- function(lambda, p, n_samples = 1){
    
    # sample component id
    comp_id <- sample(x = 1:length(lambda), 
                           size = n_samples, 
                           prob = p,
                           replace = TRUE)
    # choose correct component, sample from corresponding distribution
    z_pois <- rpois(n = n_samples, lambda = lambda[comp_id])
    
    return(z_pois)
    
  }

  # can also put simulations into a data frame first, then plot...
  mix_df <- tibble(
    z = sim_poisson_mix(c(1,4,8,15), 
                        p = c(0.1,0.2,0.1,0.6), 
                        n_samples = 1000)
  )
  
  ggplot(data = mix_df, aes(x = z)) +
    
    geom_histogram(aes(y = ..density.. ), 
                   binwidth = 1, colour = "white") +
    
    theme_bw()

```

***