---
title: "MXB107 Worksheet 1"
author: "Gentry White, Andy Jones, Steven Kedda & Lachlan Griffin"
date: "`r Sys.Date()`"
output: tint::tintHtml
bibliography: ../src/worksheets.bib
link-citations: yes
header-includes:
    - \usepackage{fancyhdr}
    - \usepackage{floatrow}
    - \floatsetup[figure]{capposition=top}
params:
  tutor_name: "Andy"
  show_solutions: FALSE
---

```{r template-header, child='../src/template-header.Rmd', eval = TRUE}

```

```{r ws-setup, include=FALSE}
  # if problems with knitting directory:
  # set Knit Directory = Document Directory

  # install libraries needed for worksheet
  library(dplyr)
  library(ggplot2)

  # Make notes here:
  # --- chunk `instructions-header` currently turned off. 
  #     Set `eval = TRUE` to use (and update file).
  #
  #

```

> The simple graph has brought more information to the data analyst’s mind than any other device
>
> `r tint::quote_footer('---John Tukey')` 

```{r instructions-header, child='../src/instructions-header.Rmd', eval = FALSE, echo=FALSE}
  
```


# Recap: SECTION

# Theory questions

```{r theory-question, child='../question-bank/idwk01T.Rmd', eval = TRUE}
  
```

# Practical questions

**Question 1**

```{r prac-question-1, child='../question-bank/idwk0101-automaticComparison.Rmd', eval = TRUE}
  
```

**Question 2**

```{r prac-question-2, child='../question-bank/idwk0102-engineDisplacement.Rmd', eval = TRUE}
  
```

**Question 3**

```{r prac-question-3, child='../question-bank/idwk0103-efficiencyPlot.Rmd', eval = TRUE}
  
```
